### ISSUE TITLE
Use websocket for displaying messages in real time

### ISSUE THREAD

**Issue by sudo001** [n1d3v/naticord#11]
Using HTTPs for loading past messages is great, however it is not good for displaying messages in real time - thats what websocket was made for.

Will be easy to implement and u will avoid possible ratelimits.

**Comment by axeltechtips** [comment]
good idea!

**Comment by n1d3v** [comment]
Yes, I have been working on websockets for the past few days and I have gotten a bit of it to work. I will soon update the app to have some more fixes and also this
