### ISSUE TITLE
Discord token not saved after reopening Naticord

### ISSUE THREAD

**Issue by kensuke101-1** [n1d3v/naticord#12]
https://github.com/n1d3v/naticord/assets/131302964/2398de49-ab68-433a-953d-7ac257675741

There is no **Config.ini** file saved in my user folder, even though it says that it should do that on your Github repo.

**Comment by Shavixinio** [comment]
I don't have a specific fix for that, but for now as a workaround, you could try and make a `config.ini` file in the user folder, and paste in the content:
```
[auth]
token = YourToken
```

**Comment by Shavixinio** [comment]
I just noticed that you're using the PyQt6 version of Naticord, and in the code the file isn't `config.ini` anymore, it's `settings.ini`, but I think in the code there's no mentions of any file like this getting made if I'm not wrong. I'll look into this and figure out what's up.

**Comment by kensuke101-1** [comment]
> I just noticed that you're using the PyQt6 version of Naticord, and in the code the file isn't `config.ini` anymore, it's `settings.ini`, but I think in the code there's no mentions of any file like this getting made if I'm not wrong. I'll look into this and figure out what's up.

When I checked the settings.ini file, it only saved if dark mode was on. I am reinstalling Naticord now to see if that fixes it.

**Comment by kensuke101-1** [comment]
![image](https://github.com/n1d3v/naticord/assets/131302964/c1165806-a7cb-4c8c-a0de-815820fc51e4)
That did not fix it. As you can see, I am logged in, but it did not save my Discord token.

**Comment by kensuke101-1** [comment]
Is there a way to manually copy and paste in my token?

**Comment by Shavixinio** [comment]
just save your token in a txt file to use it in the future

**Comment by n1d3v** [comment]
you are using the qt6 branch which is heavily outdated and i dont plan to update it. please use the qt5 branch for updates.

**Comment by Shavixinio** [comment]
> you are using the qt6 branch which is heavily outdated and i dont plan to update it. please use the qt5 branch for updates.

maybe add it in the readme to avoid confusion
