### ISSUE TITLE
Too long

### ISSUE THREAD

**Issue by Nanapiou** [n1d3v/naticord#14]
When the account has many channel, it takes sooooo long to load all of the channels in the `load_friends` function, so long that I needed to debug the code to understand why it "didn't work".

When sending a message, there's a blank before the actual message (and the message stay in the input), and the client scroll up after a few seconds any time I try to scroll at the end of the channel.
![image](https://github.com/n1d3v/naticord/assets/88728340/7450e7d8-3b22-4533-8349-4055bbc42219)

When clicking a server, it doesn't do anything, it just changes the appearance of the icon.
![image](https://github.com/n1d3v/naticord/assets/88728340/4f4f37ec-6e85-4d91-9f99-d1c1492d593d)

**Comment by n1d3v** [comment]
This will be fixed in the rewrite of naticord in C#. This is a bug in most of the naticord versions since servers have usually been a problem and this is one of those versions. There will be a temp fix now but it's better to wait for the rewrite as it will be more stable and stuff like that.
