### ISSUE TITLE
Errors when using characters such as Ö Ä Ø Æ Å

### ISSUE THREAD

**Issue by Mestalic** [n1d3v/naticord#19]
Gives error code 400
![image](https://github.com/n1d3v/naticord/assets/87284221/73f83bde-a411-48d8-889b-9cb25119ba8f)

**Comment by Mestalic** [comment]
I don't really know a fix for this but I'll let you know if I do! Just wanted to make this so it can be fixed in the future :)

**Comment by n1d3v** [comment]
hmmm, weird. i think this might be a unicode error but ill try to replicate it.

**Comment by Mestalic** [comment]
This was from the .exe version btw i also tried the python version and on that one it works just fine sending those characters atleast

**Comment by n1d3v** [comment]
fixed in the latest release coming soon
