### ISSUE TITLE
Serious issue: Naticord taking 1 GB of RAM on idle, sending too many requests and end up getting IP blocked by Discord.

### ISSUE THREAD

**Issue by Shavixinio** [n1d3v/naticord#21]
When I closed Naticord, I found out it still works in the background and constantly keeps sending requests to Discord servers, and now me and my brother are IP blocked (probably for like 20 minutes), and DMs/Servers don't load, and it's not a server issue, the servers are working fine, only on phone the messages load, on Discord vanilla client not.

![image](https://github.com/n1d3v/naticord/assets/54279284/c7b6577f-7990-4d17-9cf5-12eb487bcd0a)

At this rate there's a chance we could get flagged as spammers and get our accounts banned. For your safety, don't use Naticord until it's fixed, or after closing it, look into the task manager and force close it there too.

**Comment by jukfiuune** [comment]
Its fixed in the newest commit

**Comment by Shavixinio** [comment]
Then it's best to make a new release very soon, I guess I have to build it from source for now

**Comment by n1d3v** [comment]
> Then it's best to make a new release very soon, I guess I have to build it from source for now

it is now fixed in 0.1.1b3
