### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Zeyzers** [n1d3v/naticord#28]
Hi,

I just downloaded your application.
When i try to login it says "Failed to login. Please check your email and password! Error: Request cancelled. Unable to create a secure SSL/TLS channel."
I'm pretty sure i'm using the right credentials of my discord account.

I'm currently using Windows 10.
If you need me to give you more information just tell me!

**Comment by n1d3v** [comment]
this is a known issue and fixed soon
