### ISSUE TITLE
Linux support and maybe a backport to .NET Framework 3.5 (for pre Win 2000)

### ISSUE THREAD

**Issue by matu6968** [n1d3v/naticord#29]
Nice project going on here, but i would like to see a Linux port as .NET Core has support for it and shouldn't be too hard to port.

Also would like to consider making a legacy version for even older systems using .NET 3.5 as there is a [WIP port for Windows 9x](https://github.com/itsmattkc/dotnet9x) and would be appriciated to see older systems get Naticord.

**Comment by n1d3v** [comment]
it is simply not possible to get naticord on net 3.5 as that would mean less compatibility and some frameworks just need .net 4.0

**Comment by matu6968** [comment]
> it is simply not possible to get naticord on net 3.5 as that would mean less compatibility and some frameworks just need .net 4.0

What about Linux support as you didn't mention it

**Comment by n1d3v** [comment]
> > it is simply not possible to get naticord on net 3.5 as that would mean less compatibility and some frameworks just need .net 4.0
> 
> What about Linux support as you didn't mention it

im working on a port in the naticord-core repo but nothing is out yet
