### ISSUE TITLE
Failed to find the selected server.

### ISSUE THREAD

**Issue by ObamiumT** [n1d3v/naticord#30]
In Naticord, when I try to open a channel inside **any server**, I get an error saying "Failed to find the selected server." Image shows:
![naticord-bug](https://github.com/n1d3v/naticord/assets/155235423/4450ad4a-95f5-423e-8884-9a97020efeff)

Version: Naticord 0.1.1 beta **3**
OS: Windows 11 x64
Installed using the setup, not using the binary.

## How to reproduce

1. Open naticord and log in
2. Go to any server
3. Open a channel
And the pop up comes out.

If you need any more information, feel free to ask.

**Comment by n1d3v** [comment]
ik
