### ISSUE TITLE
Trying to login into Naticord version 0.2 beta 2 does not work and other issues

### ISSUE THREAD

**Issue by matu6968** [n1d3v/naticord#37]
As the title says, trying to login onto latest version of Naticord using a email address results in a 400 bad request error on Windows 11, so i had to login using a token.
![Zrzut ekranu 2024-06-20 121725](https://github.com/Naticord/naticord/assets/89382946/2f66c89b-5a32-447d-ab2b-0ac0fd6c958b)

I would also like to point out more issues i noticed like the fact that the UI is messed up causing trouble seeing what are you typing, and after sending a message on a channel the whole chat vanishes and requires a reclick on the channel to see your message.

https://github.com/Naticord/naticord/assets/89382946/408263be-4cb0-4eb3-acbe-2ce67a75c553

**Comment by n1d3v** [comment]
1. Email login is being fixed. 
2. UI is messed up because of some UI mod like Rectify 11. In no way it should look like that.
3. Server is a known bug and is trying to be fixed.

I'll keep this open for progress on all 3.

**Comment by n1d3v** [comment]
> 1. Email login is being fixed.
> 
>     2. UI is messed up because of some UI mod like Rectify 11. In no way it should look like that.
> 
>     3. Server is a known bug and is trying to be fixed.
> 
> 
> I'll keep this open for progress on all 3.

Also, you might want to try getting the latest artifact from GitHub Actions. It might fix some issues.

**Comment by matu6968** [comment]
> Also, you might want to try getting the latest artifact from GitHub Actions. It might fix some issues.

AFAIK none of the issues have been fixed in a latest artifact build (i couldn't test the email login feature as i was previously logged in)

**Comment by n1d3v** [comment]
> > Also, you might want to try getting the latest artifact from GitHub Actions. It might fix some issues.
> 
> AFAIK none of the issues have been fixed in a latest artifact build (i couldn't test the email login feature as i was previously logged in)

I have made another version with a different build name and login worked perfectly fine. I am guessing this is just the issue of releasing different build targets cause debug and testing (custom one i made) works perfect. I'll try to fix all the other issues.

**Comment by n1d3v** [comment]
I have fixed the server issue in the latest commit. You can check the latest artifact and see if that solved the issue or if another arised.

**Comment by matu6968** [comment]
> I have fixed the server issue in the latest commit. You can check the latest artifact and see if that solved the issue or if another arised.

It seems like the server issue has been fixed in the latest commit along partially with the home page UI theming, but i discovered another issue where it autoplays any video with interacting with the UI itself  (forgot to turn on the sound on the recording) and the issue repeats everytime you send a message.

https://github.com/Naticord/naticord/assets/89382946/f65aa403-850f-4d0a-a0b6-609a4d5b52f5

![Zrzut ekranu 2024-06-22 122342](https://github.com/Naticord/naticord/assets/89382946/e8e286c5-2d0e-4829-a77d-b3a946aa8f93)

**Comment by n1d3v** [comment]
> > I have fixed the server issue in the latest commit. You can check the latest artifact and see if that solved the issue or if another arised.
> 
> It seems like the server issue has been fixed in the latest commit along partially with the home page UI theming, but i discovered another issue where it autoplays any video with interacting with the UI itself (forgot to turn on the sound on the recording) and the issue repeats everytime you send a message.
> 22.06.2024_12.22.40_REC.mp4
> 
> ![Zrzut ekranu 2024-06-22 122342](https://private-user-images.githubusercontent.com/89382946/341968241-e8e286c5-2d0e-4829-a77d-b3a946aa8f93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNTk5OTUsIm5iZiI6MTcxOTA1OTY5NSwicGF0aCI6Ii84OTM4Mjk0Ni8zNDE5NjgyNDEtZThlMjg2YzUtMmQwZS00ODI5LWE3N2QtYjNhOTQ2YWE4ZjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEyMzQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMDIxZTViN2RlOGIyNWRiMzcyMDAxMDE3NThhOTUyZjQ2MzQxZDIwYjk1ZmM2YjA5NDNiZTkzZThlY2QwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hfm9H5eDDdHTGZKXNvNIXs5WErtT1QsN7HuPMNCBkHw)

Didn't notice the video issue. I'll fix it later.
