### ISSUE TITLE
Windows XP support ended in later versions (likely 0.1.1 stable and newer)

### ISSUE THREAD

**Issue by matu6968** [n1d3v/naticord#38]
Windows XP supports .NET 4.0 and without any issue it used to run Naticord on it (but required using it a proxy which back then didn't offer a way to use a proxy address), but ever since later versions now i get a "C:/(insert install directory)/naticord.exe is not a valid Win32 application" error meaning some compoment or code requires .NET 4.5 or later. Why the sudden drop of Win XP support?
![image](https://github.com/Naticord/naticord/assets/89382946/fbacfdeb-7bee-48dd-86fe-d91927106d6a)

**Comment by n1d3v** [comment]
I dropped XP support in favor of better performance (async). I didn't really think anyone would use XP so dropped it. Vista is still there though.

**Comment by n1d3v** [comment]
I am working on a legacy branch where I plan to support down to 95. So if you want to check it out in the future you can.
