### ISSUE TITLE
Dark mode doesn't work + the setting doesn't get applied

### ISSUE THREAD

**Issue by hateweb** [n1d3v/naticord#39]
Dark mode doesn't work + the checkbox state doesn't get saved when pressing apply in the settings. I also tried setting dark mode manually in `%LocalAppData%\Naticord\Naticord.exe_Url_*\user.config` and nothing changed.

Build: latest release
OS: Windows 10 22H2

**Comment by n1d3v** [comment]
> Dark mode doesn't work + the checkbox state doesn't get saved when pressing apply in the settings. I also tried setting dark mode manually in `%LocalAppData%\Naticord\Naticord.exe_Url_*\user.config` and nothing changed.
> 
> Build: latest release OS: Windows 10 22H2

shouldve probably mentioned this but i didnt. dark mode is still a work in progress and doesnt work for now.
