### ISSUE TITLE
Better UX/UI

### ISSUE THREAD

**Issue by szaaamerik** [n1d3v/naticord#42]
The current GUI is kind of buggy and kinda not user-friendly, especially with custom Windows themes. If you plan on making this a Windows-only project, we can use WinUI3. Otherwise - we might consider Avalonia. I'm fairly familiar with both and this is something that you can assign to me.

I can think of and develop a UI once I am back from holiday.

**Comment by szaaamerik** [comment]
If you could, please attach the enhancement label to this issue. I've forgot to do that

**Comment by n1d3v** [comment]
I am working on a WPF remake of Naticord with an overall better UI. So this is in the making basically.

**Comment by szaaamerik** [comment]
Alright, I'll wait for once you finish said remake, and leave my honest thoughts. Also, WPF does not support NativeAOT compilation which would make the name lie to the user (I'm assuming you do actually native compile this project, since this is winforms).

**Comment by n1d3v** [comment]
> Alright, I'll wait for once you finish said remake, and leave my honest thoughts. Also, WPF does not support NativeAOT compilation which would make the name lie to the user (I'm assuming you do actually native compile this project, since this is winforms).

Fair. I mean native as in the client is not a web browser and is native design. But this I understand. I'm slowing shifting away from the native design due to me using AdonisUI in WPF but I might change the name in the future.

**Comment by szaaamerik** [comment]
Using Avalonia would make the project support Linux, Mac, and Windows all at once. This would be a nice feature as well. You can look at JetBrains Rider, which is an Avalonia project. If we can theme it nicely, it would look very nice on Naticord.

**Comment by n1d3v** [comment]
I'll take a look into Avalonia. I just want something that's easy to integrate and works in an instant with near no code changes.

**Comment by n1d3v** [comment]
![image](https://github.com/Naticord/naticord/assets/135556230/1827e122-02ba-4f38-8a97-e9e97c59450a)

Here's an example of the new UI if you want.

**Comment by szaaamerik** [comment]
Is it possible for you to add placeholder text to these textboxes? Not everyone might know what they do.

**Comment by n1d3v** [comment]
> Is it possible for you to add placeholder text to these textboxes? Not everyone might know what they do.

![image](https://github.com/Naticord/naticord/assets/135556230/64f65b11-5663-4e49-aa11-a780ae4ee477)

**Comment by szaaamerik** [comment]
That's way better.

**Comment by n1d3v** [comment]
working on a new UI with a friend. looking much better for naticord. gonna think of a new name for naticord tho.

**Comment by n1d3v** [comment]
> working on a new UI with a friend. looking much better for naticord. gonna think of a new name for naticord tho.

![image](https://github.com/Naticord/naticord/assets/135556230/0f65927a-1c04-4482-8946-0a695d2756f3)

naticord is now going to become lumina. this is figma but we are making this a reality in wpf. login screen is already done.

**Comment by szaaamerik** [comment]
The UI design in question is quite nice, although I'm afraid the name is already used for a private IDA Pro server.

**Comment by n1d3v** [comment]
I will close this issue, but I will continue updating this with comments from me.
