### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by Shavixinio** [n1d3v/naticord#7]
After opening `naticord.py`, the terminal opens for a split second, shows the text in the image below and closes instantly.

![image](https://github.com/n1d3v/naticord/assets/54279284/39acdbd1-7932-4fc2-a4f4-2dded172a5b8)

**Comment by axeltechtips** [comment]
Have you tried doing 
``pip install aiohttp``?

**Comment by Shavixinio** [comment]
![image](https://github.com/n1d3v/naticord/assets/54279284/2100365d-2d3c-41a2-bd53-cdabefbab696)

I just noticed there's something misspelled in the code too.

**Comment by Shavixinio** [comment]
Okay yeah, the spelling fix made the program work again now
